name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

defaults:
  run:
    working-directory: ./php

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: ./vendor/bin/phpunit tests

    # - name: Run a one-line script
    #   env:
    #     SUPER_SERVER: ${{ secrets.SITE_SERVER }}
    #   run: echo $SUPER_SERVER

    # - name: 📂 Sync files
    #   uses: SamKirkland/FTP-Deploy-Action@v4.3.4
    #   with:
    #     server: files.000webhost.com
    #     username: scandiweb-yakob
    #     password: "@Admin123"
